Added solution
Merkald/mate-threads pull request #1
Opened 2020-06-30 09:49 UTC by Merkald

2020-06-30 09:55 UTC, boroda4436 requested changes
@Merkald Додай пліз файл з логами, де буде вказано твої system.out і буде видно гонку потоків

2020-06-30 10:37 UTC, Merkald commented
Я додав файл з логами але так як двічі ранив програму дані дублюються

2020-06-30 12:55 UTC, Sofasmile commented on src/main/java/Main.java
> +        int[] num = {0};
пропоную створити окремий клас, в якому буде змінна та методи increment(), getValue()... 
і передавати його в окремі потоки

2020-06-30 12:55 UTC, Sofasmile commented on src/main/java/Main.java
> +        RunnableThread runnableThread = new RunnableThread(num,100);
```suggestion
        RunnableThread runnableThread = new RunnableThread(num, 100);
```

2020-06-30 12:55 UTC, Sofasmile commented on src/main/java/threads/MyThread.java
> +        while (true) {
```suggestion
        while (num[0] < limit) {
```

2020-07-01 11:09 UTC, Sofasmile approved these changes

2020-07-01 11:46 UTC, merged